#ifndef TOKENIZER_H
#define TOKENIZER_H

#include "provided.h"
#include <string>

class Tokenizer : public TokenizerBase
{
public:
    Tokenizer();
    virtual ~Tokenizer();

    virtual void tokenize(const std::string& input);
    virtual bool next(std::string& token);

private:
    std::string m_tokens;
	// stores the tokens generated by tokenize()
	size_t m_index; 
    // index of the next token to return in next()
};

#endif // TOKENIZER_H
